### ISSUE TITLE
Move to gh-pages branch

### ISSUE THREAD

**Issue by dontcallmedom** [WICG/shape-detection-api#1]
So that https://wicg.github.io/shape-detection-api works

**Comment by marcoscaceres** [comment]
Done. @miguelao, I've made "gh-pages" default also. We normally delete "master" and do feature/bug branches, but it's up to you about how you want to work.

**Comment by miguelao** [comment]
Ouch thanks folks, forgot about the branch twist. Will remove `master` and live on gh-pages.
