### ISSUE TITLE
The draft doesn't define at all what detection does

### ISSUE THREAD

**Issue by smaug----** [WICG/shape-detection-api#12]
It doesn't link to other spec nor does it define itself what is supposed to happen when one calls detect()

**Comment by miguelao** [comment]
It says [here](https://wicg.github.io/shape-detection-api/#shape-detection-in-the-wild): 
> In object-class detection "the task is to find the locations and sizes of all objects in an image that belong to a given class. Examples include upper torsos, pedestrians, and cars." [wikipedia] . Face detection, on the other hand, 

In case it's unclear, I've rewritten it so that it's more evident what the paragraph is about.

**Comment by miguelao** [comment]
Will close this issue, please reopen if necessary.
