### ISSUE TITLE
Selecting barcode formats

### ISSUE THREAD

**Issue by brason** [WICG/shape-detection-api#29]
Currently BarcodeDetector searches for every supported barcode format. To improve performance it would be nice if you could select only the formats you need.

**Comment by yellowdoge** [comment]
Yeah, I think we should provide a way for the platform to enumerate the supported formats (Mac impl detects only a few formats), so the user could select the desired ones. The detected format should also be specified in the response (see #30). I should work on a PR for this.

**Comment by yellowdoge** [comment]
Addressed by the previous commit.
Chromium bug [747199](https://bugs.chromium.org/p/chromium/issues/detail?id=747199) tracks its implementation in Chrome.
