### ISSUE TITLE
interface DetectedBarcode should contain encoding

### ISSUE THREAD

**Issue by justinribeiro** [WICG/shape-detection-api#30]
Given the idea that a frame may contain multiple, different barcode encoding during a `detect()`, it would be useful to have the the interface return `format` (similar to Android: https://developers.google.com/android/reference/com/google/android/gms/vision/barcode/Barcode.html#format), resulting in:

```
interface DetectedBarcode {
  [SameObject] readonly attribute DOMRectReadOnly boundingBox;
  [SameObject] readonly attribute DOMString rawValue;
  [SameObject] readonly attribute DOMString format;
  [SameObject] readonly attribute FrozenArray<Point2D> cornerPoints;
};
```

### Use Case
We have a series of various types of barcodes used for inventory tracking and shipping that are basically in the same processed frame. While we can run our own checks based on `rawValue`, it would be more consistent with other APIs like Android to simply return the detected format.

**Comment by yellowdoge** [comment]
Closing per the previous commits. 
https://bugs.chromium.org/p/chromium/issues/detail?id=747199 tracks implementation in Chrome.
