### ISSUE TITLE
cornerPoints in Text Detection API ?

### ISSUE THREAD

**Issue by jeromeetienne** [WICG/shape-detection-api#31]
in the [text detection section](https://wicg.github.io/shape-detection-api/#text-detection-api), i don't see the cornerPoints. is that on purpose ?

cornerPoints may be quite useful for image processing. For example we could track the blob in 2d on the subsequent images. possibly some pose estimation, if the size of the text image is known.

**Comment by yellowdoge** [comment]
Hmm I see, we're providing the boundingBox only, whereas the API supports, at least in Android, the cornerPoints individualized ([link](https://developers.google.com/android/reference/com/google/android/gms/vision/text/TextBlock)).  Adding `cornerPoints` sounds good to me, could you please submit a PR for it? (You can follow the  way it's done for [barcode detection](https://wicg.github.io/shape-detection-api/#dom-detectedbarcode-cornerpoints), and compile locally as explained in https://github.com/WICG/shape-detection-api#notes-on-bikeshedding-bicyclist)

**Comment by jeromeetienne** [comment]
will do

**Comment by yellowdoge** [comment]
Closing this per 23785c15f578cd442d655d138b616f04791a7f0a .

**Comment by yellowdoge** [comment]
https://crbug.com/762172 tracks the implementation of this in Chrome.
