### ISSUE TITLE
Is there a running implementation ?

### ISSUE THREAD

**Issue by jeromeetienne** [WICG/shape-detection-api#34]
i would like to experiment with the UI. i write stuff with ar.js and tracking.js. This API could be usefull with those javascript library.  

is there a way a running implementation of the shape-detection-api API ?

https://github.com/jeromeetienne/ar.js
https://github.com/eduardolundgren/tracking.js

**Comment by yellowdoge** [comment]
Currently Chrome Canary with chrome://flags/#enable-experimental-web-platform-features enabled implements Face, Barcode and Text Detectors in Mac and Android (caveat: Mac Text detection doesn't return decoded text, just bounding boxes).  This [codepen collection](https://codepen.io/collection/DwWVJj/) has some demos.
