### ISSUE TITLE
Text detection should be removed or split out

### ISSUE THREAD

**Issue by cynthia** [WICG/shape-detection-api#37]
I noticed that the text detection section was marked non-normative in it's entirety, which is a bit unorthodox - is this a feature that is considered essential?

This would be problematic when progressing to rec. I'd be happy to sit down and discuss a way forward on this.

**Comment by yellowdoge** [comment]
Can take it out entirely and into a new document - just didn't want to have to update links on the code, examples etc. WDYT?

**Comment by cynthia** [comment]
Sounds good to me. I can help with some of the work if needed.

**Comment by yellowdoge** [comment]
What would you say if I put it in an informative Annex? That'd make it unnecessary to update the links and it'd be pro-forma.

**Comment by ocsdk** [comment]
I don't think you'd be able to take the spec through the rec process if something that is clearly an API is in there as a note.

The two options is to figure out what is a feasible compromise (or better, improvement) spec that another implementation can easily implement consistently and change it to that, or split it out to a separate spec and take that through rec separately. I'm a but curious if any other implementors have expressed interest in the barcode and face detector - if not that would also be an issue going through rec.

**Comment by cynthia** [comment]
(Reposting, previous post was from the wrong account)

I don't think you'd be able to take the spec through the rec process if something that is clearly an API is in there as a note.

The two options is to figure out what is a feasible compromise (or better, improvement) spec that another implementation can easily implement consistently and change it to that, or split it out to a separate spec and take that through rec separately. I'm a but curious if any other implementors have expressed interest in the barcode and face detector - if not that would also be an issue going through rec.

**Comment by yellowdoge** [comment]
Also https://crrev.com/c/732248 FTR

**Comment by yellowdoge** [comment]
Marking as Fixed as per previous CLs
