### ISSUE TITLE
Support custom detected objects

### ISSUE THREAD

**Issue by huningxin** [WICG/shape-detection-api#4]
As discussed in https://discourse.wicg.io/t/rfc-proposal-for-face-detection-api/1642/20 and https://discourse.wicg.io/t/rfc-proposal-for-face-detection-api/1642/21, we could allow custom detected objects by implementing `DetectedObject` interface. 

In this way, we can 
 1. add shape type specific attributes to specific detected object interface, like landmarks of face or url of barcode.
 2. not need `ShapeType` enum anymore. 

I understand one specific shape detector should only detect one specific shape. So it doesn't need to check type in `detect` promise.

```
[NoInterfaceObject, exposed=Window,Worker]
interface DetectedObject {
   readonly attribute DOMRect boundingBox
}

interface DetectedFace {
    // readonly attribute unsigned long id;
    // readonly attribute sequence<Landmark>? landmarks;
}

DetectedFace implements DetectedObject;

// DetectedBarcode, DetectedText
```

**Comment by miguelao** [comment]
Thanks! Took all these comments in, please have a look at the mentioned commit and close this issue if it's pertinent.

**Comment by huningxin** [comment]
Thanks. Your change LGTM. Close this issue.
