### ISSUE TITLE
Windows 10, Google Chrome, BoundingBox values are all 0.

### ISSUE THREAD

**Issue by ganbat6093** [WICG/shape-detection-api#42]
Text detector api
Both detects fine, But some of values not provided
Windows 10, Google Chrome, BoundingBox values are all 0.
Mac, Google Chrome, RawValues ""

Please tell me, What version of chrome and OS does it work?

**Comment by yellowdoge** [comment]
@ganbat6093 I think this applies to Chrome, not to the spec, please provide more information in the bug I just opened there:
https://bugs.chromium.org/p/chromium/issues/detail?id=866019
