### ISSUE TITLE
Bikeshed/spec structure tips and nits

### ISSUE THREAD

**Issue by inexorabletash** [WICG/shape-detection-api#49]
Bikeshed optimizations:

* Replace `<pre class="idl">` with `<xmp class=idl>` and then `&lt;`-style escaping can be dropped
* Add `Markup Shorthands: markdown yes` to the metadata section, and then you can use:
  * `:` and `::` as shortcuts for `<dt>` and `<dd>`
  * backticks instead of `<code>`
  * ` ```js ` ... ` ``` ` to surround code examples, no need for `<div class=...><pre>`

The spec is using "domintro", a concept introduced elsewhere, for non-normative sections that explain to developers how to use the feature:

* It doesn't contain style definitions for these (which aren't present in the WICG template); those need to be copied from elsewhere for now. They should have a green/non-normative background.
* `<dfn>` (normative) should not be occurring inside `domintro` (non-normative) sections.

**Comment by yellowdoge** [comment]
Fixed by #51
