### ISSUE TITLE
Support QR code detection

### ISSUE THREAD

**Issue by huningxin** [WICG/shape-detection-api#5]
### iOS
[CIQRCodeFeature](https://developer.apple.com/library/ios/documentation/QuartzCore/Reference/CIQRCodeFeature/index.html#//apple_ref/occ/cl/CIQRCodeFeature)

### Android 
[com.google.android.gms.vision.barcode.Barcode](https://developers.google.com/android/reference/com/google/android/gms/vision/barcode/Barcode): not only QR code but also 1D bar code

**Comment by miguelao** [comment]
@huningxin please take a look and comment or close this issue if applicable, thanks!!

**Comment by huningxin** [comment]
@miguelao , thanks for this PR. I am currently on vacation. If you don't mind, I can take a look early next week.

**Comment by huningxin** [comment]
@miguelao , your change LGTM with a typo. I fixed it in PR: https://github.com/WICG/shape-detection-api/pull/9. Please take a look. I will close this issue after the typo fixed. Thanks!

**Comment by huningxin** [comment]
`BarcodeDetector` has been added. Close this issue.
