### ISSUE TITLE
Need `getSupportedLandmarks` function for FaceDetector

### ISSUE THREAD

**Issue by tomayac** [WICG/shape-detection-api#55]
Similar to [`supportedFormats`](https://wicg.github.io/shape-detection-api/#dom-barcodedetector-supportedformats) in `BarcodeDetector`, I would like to motivate a similar feature  tentatively named `getSupportedLandmarks` for the `FaceDetector` to communicate to the developer whether or not landmarks like eyes, mouth, nose, etc. are detectable; and if so, which of them.

As motivated in https://github.com/WICG/shape-detection-api/issues/54, it should actually be a static method.

**Comment by tomayac** [comment]
(Based on discussions with @surma and @reillyeon).

**Comment by surma** [comment]
Additionally: Android currently gives you a point for eyes, nose, mouth etc, while MacOS seems* to give you the actual outline.

(* Not 100% sure as it’s currently broken in Chrome Canary)

**Comment by tomayac** [comment]
Oops, this is actually a duplicate of https://github.com/WICG/shape-detection-api/issues/53. Not sure how I overlooked it, sorry.
