### ISSUE TITLE
Browser compatability

### ISSUE THREAD

**Issue by msi-matthew** [WICG/shape-detection-api#61]
Reading through the issues it looks like Shape Detection API is software compatible on macOS and Android.

<img width="540" alt="screen shot 2019-02-14 at 11 30 47 am" src="https://user-images.githubusercontent.com/36428623/52805390-133e2b80-304c-11e9-8db6-dab460d302df.png">

However when trying to run the demo at https://shape-detection-demo.glitch.me/

I get an error in Chrome Version 71.0.3578.98 (Official Build) (64-bit): 

<img width="1280" alt="screen shot 2019-02-14 at 11 35 35 am" src="https://user-images.githubusercontent.com/36428623/52805652-a8d9bb00-304c-11e9-81c9-c755494b2149.png">

And also on Chrome Version 72.0.3626.105 on Android P:

![0](https://user-images.githubusercontent.com/36428623/52805576-821b8480-304c-11e9-9762-3b492b76f9ba.png)

What is the availability of this technology for use in PWAs?

**Comment by tomayac** [comment]
Have you set the chrome://flags/#enable-experimental-web-platform-features flag? This should fix it.

**Comment by msi-matthew** [comment]
That disables the error.

What is the expected behavior?

**Comment by tomayac** [comment]
> Yes, that disabled the error.

By that you mean it works? Great!

> Is there a plan / path for hardware support?

For these kind of updates it's probably a good idea to CC: yourself on the implementation bug: https://crbug.com/728474.

**Comment by msi-matthew** [comment]
> By that you mean it works? Great!

Yes, working! It's returning an array of JSON.

> For these kind of updates it's probably a good idea to CC: yourself on the implementation bug: https://crbug.com/728474.

Will starring it add me to the cc: list?

**Comment by tomayac** [comment]
> Yes, working! It's returning an array of JSON.

Perfect! To deploy the feature on your site for users who have not set the flag, you can become part of the [Origin Trial](https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md) (be sure to read this in detail) via this [sign-up form](https://developers.chrome.com/origintrials/#/view_trial/-2341871806232657919).

> Will starring it add me to the cc: list?

You will be notified about changes, yes.

**Comment by msi-matthew** [comment]
Great! Thanks for the help today Thomas!
