### ISSUE TITLE
Support face landmarks detection

### ISSUE THREAD

**Issue by huningxin** [WICG/shape-detection-api#7]
Face landmarks detection capability of native platform:
### iOS

[CIFaceFeature](https://developer.apple.com/library/ios/documentation/CoreImage/Reference/CIFaceFeature/index.html#//apple_ref/occ/instp/CIFaceFeature/bounds): landmarks feature supports left eye, right eye, mouth
### Android

[FaceDetector.Face](https://developer.android.com/reference/android/media/FaceDetector.Face.html): landmarks feature supports left eye and right eye position (with eyes distance and middle point)
[com.google.android.gms.vision.face.Face](https://developers.google.com/android/reference/com/google/android/gms/vision/face/Face): landmarks feature supports mouth, cheek, ear, eye, nose
### RealSense SDK for Windows

[Face Module](https://software.intel.com/sites/landingpage/realsense/camera-sdk/v1.1/documentation/html/index.html?doc_face_face_tracking_and_recognition.html): landmarks detection feature supports 77 points of eye, eyebrow, nose, mouth and cheek

**Comment by yellowdoge** [comment]
neotan@ you might want to update the zh-cn translation to follow up #7 :-)

**Comment by reillyeon** [comment]
Marking this issue fixed as support for landmarks has been added to the specification.
